version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sqlx-test
      POSTGRES_PASSWORD: iam

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080